---
- name: 'Install Datadog'
  hosts: all

  vars:
    DD_API_KEY: {{ lookup('env'), 'DD_API_KEY' }}

  tasks:
  - name: 'One step install'
    shell: "DD_AGENT_MAJOR_VERSION=7 DD_API_KEY=${{ DD_API_KEY }} DD_SITE=datadoghq.com bash -c $(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script.sh)"