---
- name: 'Install Docker'
  hosts: all

  tasks:
  - name: 'Remove old packages'
    apt: 
      pkg:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      state: absent
  
  - name: 'Update packages'
    apt:
      update_cache: yes
    
  - name: 'Install prerequisites'
    apt:
     pkg:
       - ca-certificates
       - curl
       - gnupg
       - lsb-release
     state: latest
   
  - name: 'Get GPG key'
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  
  - name: 'Setting up stable repo'
    shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    
  - name: 'Updating packages'
    apt:
      update_cache: yes
      
  - name: 'Installing docker'
    apt: 
      pkg:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      state: latest
      
  - name: 'Start docker service'
    shell: "sudo systemctl start docker"
    
  - name: 'Enable on start-up'
    shell: "sudo systemctl enable docker"
